kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: rancher-demo
  namespace: fleet-local
spec:
  branch: main
  repo: https://github.com/zackbradys/rancher-customer-demos
  targetNamespace: rancher-demo
  paths: 
  - rancher-demo